name: Matrix
on:
  push

jobs:
  node-version:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 2
      matrix:
        node_version: [10, 12, 14, 16]

    steps:
      - name: Logging basic node version
        run: node -v

      - name: Installing nodejs (v16)
        uses: actions/setup-node@v3
        with:
          node-version: ${{matrix.node_version}}

      - name: check node version again
        run: node -v

