name: This a just demo test...

on:
  push:
    branches:
      - dev
      - main
  pull_request:
    branches:
      - dev

jobs:

  encript-decrypt-a-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Decrypt GPG file
        run:
          run: |
            gpg --quiet --batch --yes --decrypt --passphrase="${{ secrets.GPG_PASSPHRASE }}" --output ${{env.GITHUB_WORKSPACE}}/access-keys.json ${{env.GITHUB_WORKSPACE}}/access-keys.json.gpg

      - name: 'Print the secret file'
        run: |
          cat ${{env.GITHUB_WORKSPACE}}/access-keys.json

  run-shell-commands:
    runs-on: ubuntu-latest

    steps:
      - name: echo a string
        run: echo "hello world"

      - name: multiline script
        run: |
          node -v
          npm -v
  print-commands:
    runs-on: ubuntu-latest
    needs: [run-shell-commands]
    steps:
      - name: define variables
        env:
          HELLO : 'hello'
          WORLD : 'world'
        run: |
          echo $HELLO $WORLD
  running-secrets-in-condition-statement:
    runs-on: ubuntu-latest
    env:
      SUPER_SECRET: 'I have a secret'
    steps:
      - name: I haven't secret key
        if: ${{env.SUPER_SECRET == ''}}
        run: |
          echo "I have no a secret key" 

      - name: 'I got a secret key'
        if: ${{env.SUPER_SECRET != ''}}
        run: |
          echo "I have a secret key" 
  print-secret-keys:
    runs-on: ubuntu-latest
    steps:
      - name: I gonna show my secret key
        run: |
          echo ${{ secrets.ACCESS_TOKEN }}
        shell: bash

  running-external-action:
    runs-on: ubuntu-latest

    steps:
      - name: Simple JS action
        id: js-action
        uses: actions/hello-world-javascript-action@main
        with:
          who-to-greet: "Dean Hristov"
      - name: Log greeting time
        run: echo "${{ steps.js-action.output.time}}"


